# Generated by Django 4.2.2 on 2024-06-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgmaq', '0006_changereason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
