# Generated by Django 4.2.2 on 2024-06-11 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sgmaq', '0007_motivorechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('carimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('datecompleted_manager_approval', models.DateTimeField(blank=True, null=True)),
                ('datecompleted_client_approval', models.DateTimeField(blank=True, null=True)),
                ('datecompleted_history', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(max_length=1)),
                ('description', models.TextField(blank=True)),
                ('important', models.BooleanField(default=False)),
                ('deniedbyclient', models.BooleanField(default=False)),
                ('windows', models.BooleanField(default=False)),
                ('chassis', models.BooleanField(default=False)),
                ('wheels', models.BooleanField(default=False)),
                ('upholstery', models.BooleanField(default=False)),
                ('motivo_rechazo_manager', models.CharField(blank=True, choices=[], max_length=2, null=True)),
                ('comentario_rechazo_manager', models.TextField(blank=True, null=True)),
                ('motivo_rechazo_cliente', models.CharField(blank=True, choices=[], max_length=2, null=True)),
                ('comentario_rechazo_cliente', models.TextField(blank=True, null=True)),
                ('flag_rechazado', models.BooleanField(default=False)),
                ('carbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.carbrand')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.carmodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.client')),
                ('employee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_for_task', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgmaq.project')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_user_for_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
